# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_cpp:
    name: Build cpp files on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    steps:
      - uses: actions/checkout@v3
      
      - run: mkdir bin
      
      - name: Build cpp
        run: |
          g++ src/hello.cpp -o $bin/{bin_{matrix.os}}
      
      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: $bin/{bin_{matrix.os}}

  upload:
    name: Upload
    needs: [ build_cpp ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          
      - name: Display structure of downloaded files
        run: ls -R

      - name: Push generated files
        run: |
          date > date.txt
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          if git commit -m "Generate files by GitHub Actions"; then
            git push
          fi
          
